### ISSUE TITLE
recall and precision in the the README.md 

### ISSUE THREAD

**Issue by ccshao** [fbertran/SelectBoost#1]
There seems to be a minor issue in plots on **criterion value vs. c0 value** in readme.

The legend of the plots shows `sensitivity (precision)` and `specificity (recall)`, suggesting
precision == sensitivity and specificity == recall. 

However, the terms are defined differently accroding to wiki, i.e., sensitivity == recall, while precision and specificity are different metrics. More from the wiki link below
https://en.wikipedia.org/wiki/Precision_and_recall

In the codes, it seems the recall and pecision are returned in the 1st and 2nd places.
```
    vp <- sum(result.boost[which(x$support == 1)] >= level)
    totp <- sum(x$support == 1)
    sens <- vp/totp
    spe <- 0
    if (sum(result.boost >= level) != 0)
        spe <- vp/sum(result.boost >= level)
    ...
    return(c(sens, spe, Fscore, Fscore12, Fscore2, zeroz))
```

**Comment by fbertran** [comment]
Thanks for reporting this. Fixed by commit 2c7de42d663ef4e4d9e7e5931e222c44a55b18f9.
The readme now correctly states: recall (sensitivity), the precision (positive predictive value). Both, the help files and the code were updated. sens was replaced by recall in the code and spe by precision.
Best.
